DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS bird;
DROP TABLE IF EXISTS user_birds;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  latitude TEXT NOT NULL,
  longitude TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE bird (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  species_code TEXT NOT NULL,
  common_name TEXT NOT NULL,
  sci_name TEXT NOT NULL
);

CREATE TABLE user_birds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  bird_id INTEGER NOT NULL
);
